AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Infrastructure to build and deply AWS stacks for my personal website: lukevannamen.com

Globals: 
  Api: 
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"
      AllowCredentials: "'*'"

Resources:
  # S3Bucket:
  #   Type: AWS::S3::Bucket

  CounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Lambda/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        VisitorCount:
          Type: Api
          Properties:
            Path: /counter
            Method: get
      Environment:
        Variables: 
          databaseName : !Ref myCounterTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref myCounterTable

  myCounterTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: myCounterTable 
      AttributeDefinitions: 
        - 
          AttributeName: "Visitors"
          AttributeType: "S"
        # -
        #   AttributeName: "visitorCount"
        #   AttributeType: "N"
      KeySchema: 
        - 
          AttributeName: "Visitors"
          KeyType: "HASH"
        # -
        #   AttributeName: "visitorCount"
        #   KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST

  
  # myCounterTable:
  #   Type: AWS::Serverless::SimpleTable
  #   Properties:
  #     TableName: myCounterTable
  #     PrimaryKey: 
  #       Name: visitors
  #       Type: String



Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  VisitorCountApi:
    Description: "API Gateway endpoint URL for Prod stage for Counter function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/counter/"
  VisitorCountFunction:
    Description: "Counter Lambda Function ARN (Gets Attribute)"
    Value: !GetAtt CounterFunction.Arn
  VisitorCountFunctionIamRole:
    Description: "Implicit IAM Role created for Counter function"
    Value: !GetAtt CounterFunctionRole.Arn